def run(page, base, shots, errors):
    page.click("#nav [data-step=cycle]")
    page.get_by_role("link", name="battery power/current/SOC").click()
    page.wait_for_selector("text=Detected parameters")
    page.wait_for_selector("text=Pack current [A]")
    page.get_by_label("Load source").select_option(index=2)          # battery power
    page.wait_for_selector("text=Discharge energy")
    page.wait_for_timeout(800)
    page.screenshot(path=f"{shots}/p3_cycle_battery.png", full_page=True)
    page.get_by_role("link", name="speed only").click()
    page.wait_for_selector("text=Vehicle parameters")
    page.get_by_role("button", name="Fill example vehicle (assumed values)").click()
    page.wait_for_selector("text=Road-load forces")
    page.wait_for_timeout(800)
    page.screenshot(path=f"{shots}/p3_cycle_speed.png", full_page=True)
    page.click("#nav [data-step=crate]")
    page.get_by_role("button", name="Create profile from the limits above").click()
    page.wait_for_selector("text=add segment")
    page.screenshot(path=f"{shots}/p3_crate.png", full_page=True)
